MAP_INFO = {"BUSAN": "CONTROL", "ILIOS": "CONTROL", "LIJIANG TOWER": "CONTROL",
                "NEPAL": "CONTROL", "OASIS": "CONTROL", "DORADO": "ESCORT",
                "JUNKERTOWN": "ESCORT", "RIALTO": "ESCORT", "HAVANA" : "ESCORT", "ROUTE 66": "ESCORT",
                "WATCHPOINT: GIBRALTAR": "ESCORT", "BLIZZARD WORLD": "HYBRID", "EICHENWALDE": "HYBRID",
                "HOLLYWOOD": "HYBRID", "KING's ROW": "HYBIRD", "KING'S ROW": "HYBIRD", "VOLSKAYA INDUSTRIES": "ASSAULT",
                "WATCHPOINT GIBRALTAR": "ESCORT", "KINGS ROW": "HYBRID",
                "NUMBANI": "HYBRID", "HANAMURA": "ASSAULT", "HORIZON LUNAR COLONY": "ASSAULT",
                "PARIS": "ASSAULT", "TEMPLE OF ANUBIS": "ASSAULT", "VOLSKATA INDUSTRIES": "ASSAULT"}